apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: default
  labels: 
    name: redis-exporter
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis-exporter
    protocol: TCP
    port: 9121
    nodePort: 30921
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: redis-exporter
  name: redis-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: prom_redis:v1
        name: redis-exporter
        command:
        - "/bin/redis_exporter"
        ports:
        - containerPort: 9121
          protocol: TCP
